Users auth (Devise). Acceptance tests.
kkan/questions_answers pull request #3
Opened 2016-10-05 23:02 UTC by kkan

2016-10-06 17:48 UTC, vkurennov requested changes
Исправь замечания

2016-10-06 17:48 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params.merge(question: @question, user: current_user))
Создавай через ассоциации вопроса: `@question.answers.new(...)`

2016-10-06 17:48 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
1. Сравнивай по id, чтобы не тянуть юзера ответа из базы
2. Сделай метод User#author_of? с этой проверкой и вызывае его везде, где такая проверка понадобится.

2016-10-06 17:48 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = Question.create(question_params.merge(user: current_user))
create сразу же валидирует и сохраняет объект, поэтому нет смысла далее вызывать save. поэтому либо create, либо new + save

2016-10-06 17:48 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
Замени на вызов `User#author_of?`

2016-10-06 17:48 UTC, vkurennov commented on app/helpers/answers_helper.rb
> +module AnswersHelper
удаляй ненужные пустые файлы

2016-10-06 17:48 UTC, vkurennov commented on app/helpers/questions_helper.rb
> +module QuestionsHelper
и этот удали

2016-10-06 17:48 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        = link_to 'Delete', question_answer_path(@question, answer), method: :delete
Показывай ссылку на удаление только автору

2016-10-06 17:48 UTC, vkurennov commented on app/views/questions/show.html.slim
> += link_to_if @question.user == current_user, 'Delete', question_path(@question), method: :delete
замени проверку на вызов User#author_of?

2016-10-06 17:48 UTC, vkurennov commented on spec/acceptance/answers/create_spec.rb
> +  scenario do
Нужен сценарий, когда есть ошибки. Все ошибки проверять не надо, но то, что система юзеру ошибку показала, проверить надо

2016-10-06 17:48 UTC, vkurennov commented on spec/acceptance/answers/create_spec.rb
> +  scenario do
В сценарии надо описание давать

2016-10-06 17:48 UTC, vkurennov commented on spec/acceptance/answers/destroy_spec.rb
> +  scenario do
Есть еще 2 сценария: незалогиненный юзер не видит ссылки на удаление и не-автор тоже не видит ссылки

2016-10-06 17:48 UTC, vkurennov commented on spec/acceptance/answers/destroy_spec.rb
> +    find('span', text: attrs[:body]).parent.find_link('Delete').click
Не привязывайся к верстке, насколько это возможно. И уж тем более таких длинных цепочек быть не должно. Используй within чтобы ограничить область старницы, с которой взаимодействуешь.

2016-10-06 17:48 UTC, vkurennov commented on spec/acceptance/questions/create_spec.rb
> +  scenario do
Нужен сценарий с ошибками и сценарий для незалогиненного юзера

2016-10-06 17:48 UTC, vkurennov commented on spec/acceptance/answers/create_spec.rb
> +  scenario do
И еще нужен сценарий для незалогиненного юзера

2016-10-06 17:48 UTC, vkurennov commented on spec/acceptance/questions/destroy_spec.rb
> +  scenario do
Нужны те же сценарии, что и для удаления ответа

2016-10-06 17:48 UTC, vkurennov commented on spec/acceptance/questions/index_spec.rb
> +    2.times { expect(page).to have_content question_titles.sample }
Почему 2 раза, если вопросов 5? И чем обычный each не устроил?

2016-10-06 17:48 UTC, vkurennov commented on spec/acceptance/questions/show_spec.rb
> +    2.times { expect(page).to have_content answers.sample }
те же комментарии, что и к questions/index_spec

2016-10-06 17:48 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'creates answer in db' do
Нужен тест на то, что ответ связывается с залогиненным юзером

2016-10-06 17:48 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      it 'save new question to db' do
Нужен тест на то, что вопрос связывается с залогиненным юзером

2016-10-06 17:48 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
где тесты на ассоциации?

2016-10-10 00:28 UTC, kkan commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params.merge(question: @question, user: current_user))
Создаю через ассоциации юзера. Если через вопрос создавать, то в случаее ошибки  сохранения @question.answers.size увеличивается, и при выводе на фронте с помощью each ругается на ссылки.
```@answer = current_user.answers.new(answer_params.merge(question: @question))```

2016-10-10 00:29 UTC, kkan commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
Тоже через ассоциации юзера ищу.
```@answer = current_user.answers.find(params[:id]).destroy```

2016-10-10 00:29 UTC, kkan commented on app/controllers/questions_controller.rb
> +    @question = Question.create(question_params.merge(user: current_user))
Ну это банально описка.

2016-10-10 00:33 UTC, kkan commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
Тоже current_user.questions

2016-10-10 00:33 UTC, kkan commented on app/helpers/answers_helper.rb
> +module AnswersHelper
+
Почему ApplicationHelper не  надо удалять? Или надо?

2016-10-10 00:34 UTC, kkan commented on app/helpers/questions_helper.rb
> +module QuestionsHelper
+

2016-10-10 00:34 UTC, kkan commented on app/views/questions/show.html.slim
> += link_to_if @question.user == current_user, 'Delete', question_path(@question), method: :delete
+

2016-10-10 00:36 UTC, kkan commented on spec/acceptance/answers/destroy_spec.rb
> +    find('span', text: attrs[:body]).parent.find_link('Delete').click
Просто не знал, как найти ссылку возле конкретного вопроса.
Заменил на такой вариант (ответ же один создается):
```within('table') { click_on 'Delete' }```

2016-10-10 00:37 UTC, kkan commented on spec/acceptance/questions/index_spec.rb
> +    2.times { expect(page).to have_content question_titles.sample }
Думал: зачем все проверять, если хватит и 2х, например. Сейчас мне и самому такая логика кажется странноватой.

2016-10-11 14:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params.merge(question: @question, user: current_user))
Ты можешь в видах использовать проверку answer.persisted?, чтобы выводить только сохраненные ответы. Ну либо так, как у тебя сейчас тоже вполне неплохо

2016-10-11 14:01 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
Напрасно убрал тесты, они как раз нужны. А что если такой проверки не будет в контроллере (например, кто-то ошибочно удалит)? Ты об этом не узнаешь, а при этом можно будет удалить ответ прямым запросом в обход видов.

На все условия обязательно должны быть тесты.

2016-10-11 14:02 UTC, vkurennov commented on app/helpers/answers_helper.rb
> +module AnswersHelper
Надо все пустые

2016-10-11 14:02 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
А, стоп. Понял идею. Да, это вариант, можно и так.

2016-10-11 14:09 UTC, vkurennov approved these changes
Принято, но допиши тесты

2016-10-11 14:09 UTC, vkurennov commented on app/models/user.rb
> +  def author_of? entry
При объявлении метода заключай список аргументов в скобки, так принято по стилю

2016-10-11 14:09 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Хотя, тест на то, что удаление чужого ответа не просиходит все же нужен. Ведь если код отрефакторится и мы уберем поиск через current_user, то появится возможность удалить ответ напрямую через запрос, а мы об этом не узнаем. Так что тест на такое важное условие все же нужен

2016-10-11 14:09 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
И тут добавь тест на то, что чужой вопрос не удаляется

2016-10-11 14:09 UTC, vkurennov commented on spec/models/user_spec.rb
> +    expect(user.author_of?(question)).to be_truthy
Для методов-предикатов надо тестировать оба варианта: когда true возвращается и когда false

2016-10-12 20:01 UTC, merged